run:
  deadline: 6m

linters:
  disable-all: true
  enable:
    - bodyclose
    - gocritic
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - lll
    - prealloc
